'1':
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: PLAYER_HEAD
  meta:
    ==: ItemMeta
    meta-type: SKULL
    display-name: §71 Peso
    internal: H4sIAAAAAAAAAONiYOBi4AnOLs3JCSjKT8vMSeVmYPJMYWBgYLkosFKh+Z/Dw7mtO51qBWff52LgAiopSC0qyUwt5mTgKEmtKCktSi3mAipm5GBgDUvMKU1l2JJa6WUQFZFhkBLhlZNc6WkG5IcEG+T4e2YVmHvmhVUmOXuaeeYC5T0czXwqLZHUmpYkhpvmRBp7ZUTlBZYm5YYZ+BgH5aR6BBkm54aW+YcHVkRWRZr45QLlXSINokLSTf1D/HKjXJyyI6tCjSLDw7J8gWzf3MCqyBBXE78sv2xfF9cq36psA98qV0PfEEcT3ypfU9/c0Kqo3MhyP3e/XN9gL8u0CANboA8YAFwFWgkKAQAA
'10':
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: PLAYER_HEAD
  meta:
    ==: ItemMeta
    meta-type: SKULL
    display-name: §310 Pesos
    internal: H4sIAAAAAAAAAE2OTU6DQBzF/5qaVPQwQ7A0jXHhR2iHFBCYAjO7FqalMFMrH23pFbxBT+HSw5i4Mp7BnbN09fJ+77d4GoAG12HZCvFcvSzXgl/BOc4AoPfz+ntr1ePe6Xv/9fn2kWqgKWXLq2bN60voN/zQtBWvNSWf9eEimouWwzvvbMSSHGWJLdIOm6qTEAkPF9sh3kTd4hGbWKp9cm9Ou9E/d9DM44Gghp2zjd8uZISmRiD4JNBTOdvR2C3d40PBiH/jkJXuPVkFJb5B40C6EitGDS9mpUrkSla6xcqgx/TgFJlkYytnpERMRor7e4fMdBbao2WC7tR7+AOlV0AMBgEAAA==
'20':
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: PLAYER_HEAD
  meta:
    ==: ItemMeta
    meta-type: SKULL
    display-name: §a20 Pesos
    internal: H4sIAAAAAAAAAE3PS07DMBgEYINAKgFuwQFchQQViQWioXVUOyR1Xt61ias8fpeqTVrio+QcrLgFl0FiR5asRqP5NmMgZKCbZd0CvO3fNyXIa3ROcoTQBf+6+77tnaL/Jf2PJx8NZAxkJ/dNKQ9XaNTIj6bdy4Mx4LMRuoxW0Er0KTsXi6TAeeJC1hF76HyJwSPV7oFso279Qmyihn3+bC+6yT9rNavYgtR0C7H127WK8MIMQM6DcabCo8cBmM5VGodjqh2dqteKcihF5WDGM1NMwxOd1lpw36S6gFQNORM140HBZgHQ2OmY9k0W+ycRU4txei9Kd7JJ8NPwAP0BFuDkVAoBAAA=
'50':
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: PLAYER_HEAD
  meta:
    ==: ItemMeta
    meta-type: SKULL
    display-name: §e50 Pesos
    internal: H4sIAAAAAAAAAE3PQU7CQBiG4V+jCVYP4dKdA01rWLgwEGUapkiZlnbiQiiD7fQfJKUFO2vP4Ek8gOdwqRexS5df3mfzWQAWXMyKGvGxfF3nKM/hmK4A4OT7+f3q53Lw9JFf/37NeWyB1ZKtLKtc7s6gU8m3qi7lzmrxUQdOowXWEj5l4xERZ2QVe5g21G03nxGcULW9oZuoWQ6oS3XbR3fuuOn/s061mDuY2F4mNtN6qSMytgOUo6Cb6nAvOOsJXhChhGImyJgJia8infRCkvDiIJSHTIWObxIzGSImqrDZEDPGaeMb1vVNoIVKD0JPiXi4z3z10mW511/H5LZ9AH+/hWw3CgEAAA==
helpbook:
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: WRITTEN_BOOK
  meta:
    ==: ItemMeta
    meta-type: BOOK_SIGNED
    title: Peso Book
    author: TallYate
    pages:
    - "§6§lPeso Plugin\n§0=-=-=-=-=-=-=-=-=-=\n\nInformation on the economy part of\
      \ the peso plugin can be found by typing \n§1§l/help peso\n§r§\n\n\n\n§3§lDIAMONDS§\
      0\nare 20 pesos each"
    - |-
      §6§lPeso Shops
      §0=-=-=-=-=-=-=-=-=-=
      Peso shops can be created by renaming a chest in an anvil to

      §0§lPesoShop §2§lx
      §0
      x will be the price to buy the all the items in from a certain slot in the chest. You will get a cheque that you may
      §0§l/deposit
    - |-
      §4§lAdmin Stuff
      §0=-=-=-=-=-=-=-=-=-=
      Admin commands must be prefaced with §0§l/peso§r

      §4§lAdminOverride
      §0Allows you to steal from and destroy other shops

      §4AdminSetDenomination
      §0do §0§lNOT§r §0type this
